### ISSUE TITLE
Text from signs aren't affected by the depth of field effect.

### ISSUE THREAD

**Issue by Theoyeah** [ABUCKY0/BetterRTX-Installer#15]
**Describe the bug**

Text from signs aren't affected by the depth of field effect.

**To Reproduce**
1. Just join a mc world with betterRTX & depth of field installed
2. Be near a sign with written text
3. Place a block and move the camera to look in the block so it can do the effect
4. See bug

**Expected behavior**

The text should clearly be affected.

**Screenshots**
![image](https://github.com/ABUCKY0/BetterRTX-Installer/assets/97792861/649a0697-0422-4357-b269-2b3f6f2cb7fc)

**Desktop:**
 - OS: Windows 11 Home
 - Browser: Microsoft Edge
 - Version 22H2 (build 22621.1776)
 - RTX: Nvidia Geforce RTX 3070 Laptop GPU
 - Processor: AMD Ryzen 5600H
 - RAM: 16GB 3200mHz

**Comment by ABUCKY0** [comment]
Sadly this is a bug that can put be fixed with BetterRTX. Here's why:

1. Sign text js rasterized, meaning that it's unaffected by the Raytracing renderer. I believe that the renderer doesn't even know that the sign has text or not.

2. In order to fix this, Mojang would have to implement the ability for the renderer to see the text.

This is also an issue without BetterRTX.
